### ISSUE TITLE
Using sudo for unarchiving

### ISSUE THREAD

**Issue by lisandro52** [nodeit/webdev_workflows_tutorial2#1]
Hey nodeit! 
While reading the tutorial, I found that when you want to run the task `Unarchive node.js tarball` as is from your tutorial, it gives the following error:

```
failed: [default] => {"failed": true}
msg: Destination '/usr/local' not writable
```

I had to add `sudo: True` to my `playbook.yml`. After that, it worked so I didn't mind it. 
But later on I see that you added `ansible.sudo = true` to the Vagrantfile but forgot to mention it earlier! :yum:

**Comment by nodeit** [comment]
Thanks for pointing that out! I've updated the tutorial so that this is explained before running any ansible commands.
